book_management/urls.py
from book_management import views
from django.urls import path

app_name = 'book_management'

urlpatterns = [
    path('new', views.NewBookView.as_view(), name='new-book'),
    path('ajax-search-book', views.ajax_search_book, name='ajax-search-book'),
]

books_base_folder/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from . import views
from . import settings

urlpatterns = [
    path('grass', views.GrassView.as_view(), name='grass'),
    path('', views.HomepageView.as_view(), name='home'),
    path('search', views.SearchView.as_view(), name='search'),
    path('statistics', views.StatisticsView.as_view(), name='statistics'),
    path('user/', include('user_management.urls')),
    path('books/', include('book_management.urls')),
    path('comments/', include('comment_management.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('view/<int:pk>/public', views.PublicBookPageView.as_view(), name='view-public-book'),
    path('view/<int:pk>/private', views.PrivateBookPageView.as_view(), name='view-private-book'),
    path('notifications', views.NotificationsView.as_view(), name='notifications'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

user_management/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from user_management import views

app_name = 'user_management'

urlpatterns = [
    path('registration', views.UserCreateView.as_view(), name='registration'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/view', views.UserProfileView.as_view(), name='view-profile'),
    path('profile/create', views.CreateProfileView.as_view(), name='create-profile'),
    path('profile/update', views.UpdateProfileView.as_view(), name='update-profile'),
    path('profile/delete', views.DeleteProfileView.as_view(), name='delete-profile'),
    path('delete', views.DeleteUserView.as_view(), name='delete-user'),
    path('profile/settings', views.ProfileSettingsView.as_view(), name='user-settings'),
    path('profile/settings/password', views.UpdatePasswordView.as_view(), name='user-password'),
    path('profile/<int:pk>/bookshelf', views.BookshelfView.as_view(), name='bookshelf'),
    path('profile/bookshelf/new-book', views.BookshelfNewBook.as_view(), name='bookshelf-new-book'),
    path('profile/bookshelf/<int:pk>/update', views.UpdateBookInfo.as_view(), name='bookshelf-update-book'),
    path('profile/bookshelf/reading/update', views.UpdateReadingBooks.as_view(), name='update-reading-books'),
    path('profile/bookshelf/read/update', views.UpdateReadBooks.as_view(), name='update-read-books'),
    path('profile/bookshelf/mustread/update', views.UpdateMustReadBooks.as_view(), name='update-must-read-books'),
    path('profile/following', views.FollowingUsersListView.as_view(), name='following-profiles'),
    path('profile/update/picture', views.UpdateProfilePictureView.as_view(), name='update-profile-picture'),
    path('email/verification_needed', views.EmailVerificationNeededView.as_view(), name='email-verification-needed'),
    path('email/verified', views.EmailVerifiedView.as_view(), name='email-verified'),
    path('report', views.ReportView.as_view(), name='report'),
    path('verify/<str:user_id_b64>/<str:user_token>', views.verify_user_email, name='verify-user-email'),
    path('ajax-save-follow', views.ajax_save_follow, name='ajax-save-follow'),
    path('ajax-check-username-exists', views.ajax_check_username_exists, name='ajax-check-username-exists'),
    path('ajax-delete-book', views.ajax_delete_book, name='ajax-delete-book'),
    path('ajax-move-book', views.ajax_move_book, name='ajax-move-book'),
    path('ajax-new-book', views.ajax_new_book, name='ajax-new-book'),
]

user_management/views.py
from django.contrib.auth import login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.auth.views import LoginView
from django.http import JsonResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, TemplateView, UpdateView, DeleteView, FormView
from django.utils.translation import gettext_lazy as _

from books_base_folder.views import SearchMixin
from book_management.decorators import profile_book_exists_only
from user_management.forms import UpdateBookInfoCrispyForm
from book_management.models import Book
from user_management.decorators import has_profile_only, has_not_profile_only
from user_management.forms import PlatformUserCreationForm, LoginForm, UpdateProfileCrispyForm, CreateProfileCrispyForm, \
    UpdateProfilePictureCrispyForm, SearchBookCrispyForm, UpdatePasswordCrispyForm
from user_management.models import Profile, ProfileBook

account_activation_token = PasswordResetTokenGenerator()


class UserCreateView(CreateView):
    """
    User CreateView.
    It contains PlatformUserCreationForm.
    """
    form_class = PlatformUserCreationForm
    template_name = 'registration/registration.html'
    success_url = reverse_lazy('user_management:email-verification-needed')

    def form_valid(self, form):
        """
        Completes the User creation, deactivating the User and sending a confirmation email.
        """
        response = super(UserCreateView, self).form_valid(form)

        mail_subject = _('Bookcamp, email di conferma account')
        relative_confirm_url = reverse(
            'user_management:verify-user-email',
            args=[
                urlsafe_base64_encode(force_bytes(self.object.pk)),
                account_activation_token.make_token(self.object)
            ]
        )

        self.object.email_user(
            subject=mail_subject,
            message=_(f'''Ciao {self.object.username}, '''
                      + '''ti diamo il benvenuto in Bookcamp.\n'''
                      + '''\nClicca il seguente link per confermare la tua email:'''
                      + f'''\n{self.request.build_absolute_uri(relative_confirm_url)}\n'''
                      + '''\nA presto, \nil Team di Bookcamp.''')
        )

        self.object.token_sent = True
        self.object.is_active = False
        self.object.save()

        return response


def user_login_by_token(request, user_id_b64=None, user_token=None):
    """
    Checks if the token matches that of the User trying to verify the email.
    """
    try:
        uid = force_str(urlsafe_base64_decode(user_id_b64))
        user = get_user_model().objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, get_user_model().DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, user_token):
        user.is_active = True
        user.save()
        login(request, user)
        return True

    return False


def verify_user_email(request, user_id_b64=None, user_token=None):
    """
    :return: Email successfully verified page, if the token matches that of the User.
    """
    if not user_login_by_token(request, user_id_b64, user_token):
        message = _('Errore. Tentativo di validazione email per l\'utente {user} con token {token}')

    return redirect('user_management:email-verified')


class LoginUserView(LoginView):
    """
    Login View.
    It contains LoginForm.
    """
    form_class = LoginForm
    template_name = "registration/login.html"
    success_url = reverse_lazy('home')


class EmailVerificationNeededView(TemplateView):
    template_name = 'user_management/email_verification_needed.html'


class EmailVerifiedView(LoginRequiredMixin, TemplateView):
    template_name = 'user_management/email_verified.html'


class ReportView(LoginRequiredMixin, TemplateView):
    template_name = "comment_management/report.html"


class UserProfileView(LoginRequiredMixin, TemplateView):
    """
    Profile TemplateView.
    """
    template_name = "user_management/user_profile.html"

    def dispatch(self, request, *args, **kwargs):
        """
        Redirects to a different page if the User has not a Profile and it is not the owner of the Profile.
        """
        user_obj = get_user_model().objects.get(pk=self.kwargs['pk'])
        if not user_obj.has_profile and not user_obj == self.request.user:
            self.template_name = "user_management/profile_not_exists.html"
        return super(UserProfileView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """
        Retrieves User info.
        """
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context['user_for_profile'] = get_user_model().objects.get(pk=self.kwargs['pk'])
        return context


@method_decorator([login_required, has_not_profile_only], name='dispatch')
class CreateProfileView(CreateView):
    """
    Profile CreateView.
    It contains CreateProfileCrispyForm.
    """
    form_class = CreateProfileCrispyForm
    template_name = 'user_management/create_profile.html'

    def form_valid(self, form):
        """
        Collects needed info to complete the Profile creation.
        """
        self.object = form.save(commit=False)
        self.object.user_id = self.request.user.pk
        self.object.save()

        return super().form_valid(form)

    def get_success_url(self):
        """
        :return: redirect towards the page 'view-profile' of the just created Profile.
        """
        return reverse_lazy('user_management:view-profile', kwargs={'pk': self.request.user.pk})


@method_decorator([login_required, has_profile_only], name='dispatch')
class UpdateProfileView(UpdateView):
    """
    Profile UpdateView.
    It contains UpdateProfileCrispyForm.
    """
    model = Profile
    form_class = UpdateProfileCrispyForm
    template_name = "user_management/update_profile.html"

    def get_object(self, queryset=None):
        """
        Retrieves Profile object of the requesting User.
        """
        return Profile.objects.get(pk=self.request.user.profile.pk)

    def get_success_url(self):
        """
        :return: redirect towards the page 'view-profile' of the just created Profile.
        """
        return reverse_lazy('user_management:view-profile', kwargs={'pk': self.request.user.pk})


@method_decorator([login_required, has_profile_only], name='dispatch')
class UpdateProfilePictureView(UpdateView):
    """
    Profile picture UpdateView.
    It contains UpdateProfilePictureCrispyForm.
    """
    model = Profile
    form_class = UpdateProfilePictureCrispyForm
    template_name = "user_management/update_profile_picture.html"

    def get_object(self, queryset=None):
        """
        Retrieves Profile object of the requesting User.
        """
        return Profile.objects.get(pk=self.request.user.profile.pk)

    def get_success_url(self):
        """
        :return: redirect towards the page 'view-profile' of the just created Profile.
        """
        return reverse_lazy('user_management:view-profile', kwargs={'pk': self.request.user.pk})


class ProfileSettingsView(LoginRequiredMixin, TemplateView):
    """
    Profile settings TemplateView.
    """
    template_name = "user_management/user_settings.html"


class UpdatePasswordView(LoginRequiredMixin, UpdateView):
    """
    Password UpdateView.
    """
    model = get_user_model()
    template_name = "user_management/update_password.html"
    form_class = UpdatePasswordCrispyForm

    def get_object(self, queryset=None):
        """
        Retrieves Profile object of the requesting User.
        """
        return get_user_model().objects.get(pk=self.request.user.pk)

    def post(self, request, *args, **kwargs):
        """
        Manages redirection when the cancel button is clicked.
        """
        if "cancel" in request.POST:
            url = reverse_lazy('user_management:view-profile', kwargs={'pk': self.request.user.pk})
            return HttpResponseRedirect(url)
        return super(UpdatePasswordView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        """
        Checks that the old password matches.
        """
        if self.request.user.check_password(form.cleaned_data['old_password']):
            return super(UpdatePasswordView, self).form_valid(form)
        else:
            return HttpResponseBadRequest()

    def get_success_url(self):
        """
        :return: redirect towards the page 'login' of the User that has just updated the password.
        """
        return reverse_lazy('user_management:view-profile', kwargs={'pk': self.request.user.pk})


@method_decorator([login_required, has_profile_only], name='dispatch')
class FollowingUsersListView(TemplateView):
    """
    Following Users ListView.
    """
    model = Profile
    template_name = "user_management/following_users_list.html"


class DeleteUserView(LoginRequiredMixin, DeleteView):
    """
    User DeleteView.
    """
    model = get_user_model()
    template_name = "user_management/delete_user.html"
    success_url = reverse_lazy("user_management:login")

    def get_object(self, queryset=None):
        """
        Retrieves User object of the requesting User.
        """
        return get_user_model().objects.get(pk=self.request.user.pk)


class DeleteProfileView(LoginRequiredMixin, DeleteView):
    """

user_management/templates/user_management/base_profile_form.html
{% extends 'base_full_page_box.html' %}
{% load crispy_forms_tags %}

{% comment %}
    Base template of a Profile form.
{% endcomment %}

{% block first_column_classes %}unnecessary-column{% endblock %}
{% block second_column_content %}
    <div class="mb-5">
        <h6 class="font-5">{% block form_page_path %}{% endblock %}</h6>
        <h5 class="font-6">{% block form_title %}{% endblock %}</h5>
        {% block form_user_profile_picture %}{% endblock %}
    </div>
    {% crispy form %}
    <div class="d-flex column-flex align-items-start mobile-column-center mt-4 mb-2">
        <div class="d-flex align-items-center justify-content-between site-flex-buttons">
            <input class="btn site-btn w-100" type="submit" form="{% block submit_button_form_id %}{% endblock %}"
                   value="{% block submit_button_value %}{% endblock %}">
            <a class="site-link font-6 ml-3 mt-3 mt-lg-0" href="{% block cancel_button_url %}{% endblock %}">
                Annulla
            </a>
        </div>
    </div>
{% endblock %}
{% block third_column_classes %}unnecessary-column{% endblock %}

user_management/templates/user_management/base_profiles_list.html
{% extends 'base_list.html' %}

{% comment %}
    Base template of a Profile list.
{% endcomment %}

{% block list_content %}
    {% for profile in profiles %}
        <div class="text-element">
            <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"
               href="{% url 'user_management:view-profile' profile.user.pk %}">
                <div class="media d-flex align-items-center">
                    <img class="rounded-picture-medium align-self-center" src="{{ profile.picture.url }}">
                    <div class="media-body ml-3">
                        <span class="font-6 break-word">{{ profile.get_name|truncatechars:40 }}</span> <br>
                        <span class="font-4 break-word">{{ profile.user.email }}</span>
                    </div>
                </div>
                {% if is_topics %}
                    <div>
                        <span class="font-6">{{ profile.user.topics_count }}</span>
                    </div>
                {% endif %}
                {% if is_comments %}
                    <div>
                        <span class="font-6">{{ profile.user.comments_count }}</span>
                    </div>
                {% endif %}
            </a>
        </div>
    {% empty %}
        <div class="ml-5 mt-5 mb-3">
            <h5 class="font-6 text-muted">Nessun utente trovato.</h5>
        </div>
    {% endfor %}
{% endblock %}

user_management/templates/user_management/create_profile.html
{% extends 'user_management/base_profile_form.html' %}

{% comment %}
    Profile CreateView page.
{% endcomment %}

{% block title %}{{ block.super}} Crea profilo{% endblock %}

{% block form_page_path %}
    <a class="site-link" href="{% url 'user_management:view-profile' user.pk %}">Profilo</a>
    &nbsp;>&nbsp;
    Crea profilo{% endblock %}
{% block form_title %}Inserisci le informazioni del profilo{% endblock %}
{% block submit_button_value %}Salva le informazioni del profilo{% endblock %}
{% block submit_button_form_id %}create-profile-crispy-form{% endblock %}
{% block cancel_button_url %}{% url 'user_management:view-profile' user.pk %}{% endblock %}

user_management/templates/user_management/delete_profile.html
{% extends 'base_delete.html' %}

{% comment %}
    Profile DeleteView page.
{% endcomment %}

{% block title %}{{ block.super }} Disabilita profilo{% endblock %}

{% block delete_page_path %}
    <a class="site-link" href="{% url 'user_management:view-profile' user.pk %}">Profilo</a>
    &nbsp;>&nbsp;
    <a class="site-link" href="{% url 'user_management:user-settings' %}">Impostazioni</a>
    &nbsp;>&nbsp;
    Disabilita profilo
{% endblock %}
{% block delete_object_title %}Disabilita il tuo profilo{% endblock %}
{% block delete_object_subtitle %}Informazioni che verranno perse definitivamente{% endblock %}
{% block delete_object_information %}
    <div class="d-flex justify-content-start align-items-center flex-wrap">
        <div>
            <img src="{{ user.profile.picture.url }}" class="rounded-picture-extra-big">
        </div>
        <div class="ml-lg-3">
            <div class="mt-3">
                <span class="font-6">Nome: </span>
                <span class="font-4">{{ user.profile.first_name }}</span>
            </div>
            <div>
                <span class="font-6">Cognome: </span>
                <span class="font-4">{{ user.profile.last_name }}</span>
            </div>
            {% if user.profile.description %}
                <div>
                    <span class="font-6">Descrizione: </span>
                    <span class="font-4">{{ user.profile.description }}</span>
                </div>
            {% endif %}
        </div>
    </div>
    <hr>
    <div class="mt-4">
        <span class="text-muted font-5">
            Tutti gli utenti che ti seguono perderanno il follow e non potranno più trovarti e vedere le tue
            informazioni. Non potrai più vedere i tuoi contenuti dal tuo profilo e le tue informazioni
            personali verranno perse. Il tuo bookshelf verrà svuotato.
        </span>
    </div>
{% endblock %}
{% block cancel_button_url %}{% url 'user_management:user-settings' %}{% endblock %}

user_management/templates/user_management/delete_user.html
{% extends 'base_delete.html' %}

{% comment %}
    User DeleteView page.
{% endcomment %}

{% block title %}{{ block.super }} Elimina account{% endblock %}

{% block delete_page_path %}
    <a class="site-link" href="{% url 'user_management:view-profile' user.pk %}">Profilo</a>
    &nbsp;>&nbsp;
    <a class="site-link" href="{% url 'user_management:user-settings' %}">Impostazioni</a>
    &nbsp;>&nbsp;
    Elimina definitivamente account
{% endblock %}
{% block delete_object_title %}Elimina definitivamente il tuo account{% endblock %}
{% block delete_object_subtitle %}Sei sicuro di voler abbandonare la piattaforma?{% endblock %}

{% block delete_object_information %}
    <span class="font-5 mt-3">
        Ci dispiace molto doverti salutare qua. Speriamo vivamente tu abbia tratto il massimo dal dialogo
        con le altre persone e abbia imparato qualcosa di nuovo.
    </span>
    <br>
    <hr>
    <span class="text-muted font-5">
    Perderai tutte le tue informazioni, i tuoi contenuti pubblicati verranno
    eliminati e non sarà più possibile recuperarli.
    </span>
{% endblock %}
{% block cancel_button_url %}{% url 'user_management:user-settings' %}{% endblock %}

user_management/templates/user_management/email_verification_needed.html
{% extends 'base.html' %}

{% comment %}
    Email confirmation required page.
{% endcomment %}

{% block title %}{{ block.super }} Conferma della mail{% endblock %}

{% block content %}
    <h3 class="font-7 d-flex justify-content-center">Controlla la tua casella di posta.</h3>
    <h5 class="font-7 text-muted d-flex justify-content-center">
        Dovresti aver ricevuto un link per confermare la tua
        email. Se l'hai già fatto puoi eseguire il &nbsp;
        <a class="site-blue-text font-7" href="{% url 'user_management:login' %}">login</a>.
    </h5>
{% endblock %}

user_management/templates/user_management/email_verified.html
{% extends 'base.html' %}

{% comment %}
    Email successfully verified page.
{% endcomment %}

{% block extra_css %}
    <style type="text/css">
        html,body {
            height: 100% !important;
            overflow: hidden;
        }
    </style>
{% endblock %}

{% block title %}{{ block.super }} Email verifcata con successo{% endblock %}

{% block header %}
    <div id="welcome-page-background" class="d-flex justify-content-center align-items-center column-flex">
        <div class="row">
            <div class="col site-col p-4">
                <h3 class="font-7 logo-font big-text mb-3 color-white-mobile">Stai per atterrare al campo base.</h3>
                <h5 class="font-7 text-muted color-white-mobile">
                    La tua email è stata verificata con successo. Entra in
                    <a class="site-blue-text font-7 site-light-blue-text-mobile" href="{% url 'home' %}">bookcamp</a>.
                </h5>
            </div>
        </div>
    </div>
{% endblock %}

user_management/templates/user_management/profile_ajax.html
<script type="text/javascript">
    /**
     * Ajax request to Follow a profile.
     * success: Calls changeFollow to manage button appearance.
     */
    function ajaxSaveFollow() {
        $.ajax({
            type: 'POST',
            url: "{% url 'user_management:ajax-save-follow' %}",
            data: {
                'user': {{ user_for_profile.pk }},
            },
            headers:{
                "X-CSRFToken": '{{ csrf_token }}'
            },
            dataType: 'json',
            beforeSend: function() {
            },
            complete: function() {
            },
            success: function(data) {
                changeFollow(data);
            }
        });
    }
</script>

user_management/templates/user_management/profile_not_exists.html
{% extends 'base.html' %}

{% comment %}
    Profile not completed page.
{% endcomment %}

{% block title %}{{ block.super }} {{ user_for_profile.username }}{% endblock %}

{% block content %}
    <div class="container-fluid site-box p-4 mb-3 bg-white w-100  mb-5 shadow-lg">
        <span class="font-7 text-danger">
            A quanto pare {{ user_for_profile.username }} non ha ancora completato il proprio profilo utente.
        </span>
    </div>
{% endblock %}

user_management/templates/user_management/registration_ajax.html
<script type="text/javascript">
    /**
     * Ajax request to find out if a username already exists.
     * success: shows an error if the username already exists, otherwise removes the error message if it was present.
     */
    $('#id_username').on('change', function () {
        $.ajax({
            type: 'GET',
            url: "{% url 'user_management:ajax-check-username-exists' %}",
            data: {
                'username': $(this).val(),
            },
            dataType: 'json',
            success: function(data) {
                let username_field = $('#id_username');

                if (data.exists) {
                    username_field.css('border-color', "#dc3545");
                    if (!$('#username-exists-error').length) {
                        username_field.after(
                            '<span id="username-exists-error" class="text-danger font-7 font-size-80">' +
                            'Un utente con questo nome è già presente.' +
                            '</span>'
                        );
                    }
                } else {
                    username_field.css('border-color', "#e8e8e8");
                    $('#username-exists-error').remove();
                }
            }
        });
    });
</script>

user_management/templates/user_management/update_password.html
{% extends 'base_full_page_box.html' %}
{% load crispy_forms_tags %}

{% comment %}
    Password update page.
{% endcomment %}

{% block title %}{{ block.super }} Aggiorna password{% endblock %}

{% block first_column_classes %}unnecessary-column{% endblock %}
{% block second_column_content %}
    <div class="mb-5">
        <h6 class="font-5">
            <a class="site-link" href="{% url 'user_management:view-profile' user.pk %}">Profilo</a>
            &nbsp;>&nbsp;
            <a class="site-link" href="{% url 'user_management:user-settings' %}">Impostazioni</a>
            &nbsp;>&nbsp;
            Modifica password
        </h6>
        <h5 class="font-6">Modifica password</h5>
    </div>
    {% crispy form %}
    <div class="mt-4 mb-2 site-flex-buttons">
        <input class="btn site-btn  mb-3 mb-lg-0" type="submit" form="update-password-crispy-form" value="Salva password">
        <a class="site-link font-6 ml-3" href="{% url 'user_management:user-settings' %}">
            Annulla
        </a>
    </div>

{% endblock %}
{% block third_column_classes %}unnecessary-column{% endblock %}

user_management/templates/user_management/update_profile.html
{% extends 'user_management/base_profile_form.html' %}

{% comment %}
    Profile update page.
{% endcomment %}

{% block title %}{{ block.super }} Modifica profilo{% endblock %}

{% block form_page_path %}
    <a class="site-link" href="{% url 'user_management:view-profile' user.pk %}">Profilo</a>
    &nbsp;>&nbsp;
    Modifica profilo
{% endblock %}
{% block form_title %}Modifica i dati del profilo{% endblock %}

{% block form_user_profile_picture %}
    <div class="media mt-4">
        <img src="{{ user.profile.picture.url }}" class="rounded-picture-medium align-self-center">
        <div class="media-body ml-3">
            <span class="font-5">{{ user.username }}</span> <br>
            <a href="{% url 'user_management:update-profile-picture' %}" class="site-blue-text font-7 no-decoration">
                Cambia l'immagine del profilo
            </a>
        </div>
    </div>
{% endblock %}
{% block submit_button_value %}Salva le informazioni del profilo{% endblock %}
{% block submit_button_form_id %}update-profile-crispy-form{% endblock %}
{% block cancel_button_url %}{% url 'user_management:view-profile' user.pk %}{% endblock %}

user_management/templates/user_management/update_profile_picture.html
{% extends 'user_management/base_profile_form.html' %}

{% comment %}
    Profile picture update page.
{% endcomment %}

{% block title %}{{ block.super }} Immagine del profilo{% endblock %}

{% block form_page_path %}
    <a class="site-link" href="{% url 'user_management:view-profile' user.pk %}">Profilo</a>
    &nbsp;>&nbsp;
    <a class="site-link" href="{% url 'user_management:update-profile' %}">Modifica profilo</a>
    &nbsp;>&nbsp;
    Immagine del profilo
{% endblock %}

{% block form_title %}Aggiorna l'immagine del profilo{% endblock %}
{% block submit_button_value %}Salva immagine{% endblock %}
{% block submit_button_form_id %}update-profile-picture-crispy-form{% endblock %}
{% block cancel_button_url %}{% url 'user_management:view-profile' user.pk %}{% endblock %}

user_management/templates/user_management/user_settings.html
{% extends 'base_full_page_box.html' %}

{% comment %}
    User settings page.
{% endcomment %}

{% block title %}{{ block.super }} Impostazioni{% endblock %}

{% block first_column_classes %}unnecessary-column{% endblock %}

{% block second_column_content %}
    <div class="mb-5">
        <h6 class="font-5">
            <a class="site-link" href="{% url 'user_management:view-profile' user.pk %}">Profilo</a>
            &nbsp;>&nbsp;
            Impostazioni</h6>
        <h5 class="font-6">Impostazioni</h5>
    </div>
    <div>
        <a href="{% url 'user_management:user-password' %}"
           class="site-blue-text font-6">Modifica password</a> <br>
        <span class="text-muted">
            Modifica la tua password.
        </span>
    </div>
    <hr>
    <div>
        {% if user.has_profile %}
            <a href="{% url 'user_management:delete-profile' %}" class="site-red-text font-6">Disabilita profilo</a> <br>
            <span class="text-muted">
                Tutti gli utenti che ti seguono perderanno il follow e non potranno più trovarti e vedere le tue
                informazioni. Non potrai più vedere i tuoi contenuti dal tuo profilo e le tue informazioni
                personali verranno perse.
            </span>
        {% else %}
            <a href="{% url 'user_management:create-profile' %}" class="site-blue-text font-6">Crea profilo</a> <br>
            <span class="text-muted">
                Potrai vedere i tuoi contenuti pubblicati, gli elementi salvati o che ti piacciono di altri utenti
                e i profili che segui. Potrai salvare i libri nel tuo bookshelf e gli altri utenti potranno seguirti.
            </span>
        {% endif %}
    </div>
    <hr>
    <div>
        <a href="{% url 'user_management:delete-user' %}"
           class="site-red-text font-6">Cancella definitivamente il mio account</a> <br>
        <span class="text-muted">
            Attenzione! Tutte le tue informazioni e i tuoi contenuti pubblicati verranno
            eliminati e non sarà più possibile recuperarli.
        </span>
    </div>
{% endblock %}

{% block third_column_classes %}unnecessary-column{% endblock %}