book_management/urls.py
from book_management import views
from django.urls import path

app_name = 'book_management'

urlpatterns = [
    path('new', views.NewBookView.as_view(), name='new-book'),
    path('ajax-search-book', views.ajax_search_book, name='ajax-search-book'),
]

books_base_folder/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from . import views
from . import settings

urlpatterns = [
    path('grass', views.GrassView.as_view(), name='grass'),
    path('', views.HomepageView.as_view(), name='home'),
    path('search', views.SearchView.as_view(), name='search'),
    path('statistics', views.StatisticsView.as_view(), name='statistics'),
    path('user/', include('user_management.urls')),
    path('books/', include('book_management.urls')),
    path('comments/', include('comment_management.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('view/<int:pk>/public', views.PublicBookPageView.as_view(), name='view-public-book'),
    path('view/<int:pk>/private', views.PrivateBookPageView.as_view(), name='view-private-book'),
    path('notifications', views.NotificationsView.as_view(), name='notifications'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

user_management/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from user_management import views

app_name = 'user_management'

urlpatterns = [
    path('registration', views.UserCreateView.as_view(), name='registration'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/view', views.UserProfileView.as_view(), name='view-profile'),
    path('profile/create', views.CreateProfileView.as_view(), name='create-profile'),
    path('profile/update', views.UpdateProfileView.as_view(), name='update-profile'),
    path('profile/delete', views.DeleteProfileView.as_view(), name='delete-profile'),
    path('delete', views.DeleteUserView.as_view(), name='delete-user'),
    path('profile/settings', views.ProfileSettingsView.as_view(), name='user-settings'),
    path('profile/settings/password', views.UpdatePasswordView.as_view(), name='user-password'),
    path('profile/<int:pk>/bookshelf', views.BookshelfView.as_view(), name='bookshelf'),
    path('profile/bookshelf/new-book', views.BookshelfNewBook.as_view(), name='bookshelf-new-book'),
    path('profile/bookshelf/<int:pk>/update', views.UpdateBookInfo.as_view(), name='bookshelf-update-book'),
    path('profile/bookshelf/reading/update', views.UpdateReadingBooks.as_view(), name='update-reading-books'),
    path('profile/bookshelf/read/update', views.UpdateReadBooks.as_view(), name='update-read-books'),
    path('profile/bookshelf/mustread/update', views.UpdateMustReadBooks.as_view(), name='update-must-read-books'),
    path('profile/following', views.FollowingUsersListView.as_view(), name='following-profiles'),
    path('profile/update/picture', views.UpdateProfilePictureView.as_view(), name='update-profile-picture'),
    path('email/verification_needed', views.EmailVerificationNeededView.as_view(), name='email-verification-needed'),
    path('email/verified', views.EmailVerifiedView.as_view(), name='email-verified'),
    path('report', views.ReportView.as_view(), name='report'),
    path('verify/<str:user_id_b64>/<str:user_token>', views.verify_user_email, name='verify-user-email'),
    path('ajax-save-follow', views.ajax_save_follow, name='ajax-save-follow'),
    path('ajax-check-username-exists', views.ajax_check_username_exists, name='ajax-check-username-exists'),
    path('ajax-delete-book', views.ajax_delete_book, name='ajax-delete-book'),
    path('ajax-move-book', views.ajax_move_book, name='ajax-move-book'),
    path('ajax-new-book', views.ajax_new_book, name='ajax-new-book'),
]

user_management/models.py
from collections import defaultdict
from datetime import date

from PIL import Image

from django.conf import settings
from django.contrib.auth.models import User, AbstractUser
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import MaxValueValidator
from django.db import models
from django.db.models import Count
from django.utils.translation import gettext_lazy as _

from book_management.models import Book
from comment_management.models import Topic, Bookmark


class PlatformUser(AbstractUser):
    AbstractUser._meta.get_field('email')._unique = True

    # terms_of_service_acceptance = models.BooleanField(default=False)
    # terms_of_service_acceptance_datetime = models.DateTimeField(auto_now_add=True)

    is_manager = models.BooleanField(default=False)

    def __str__(self):
        return self.username

    @property
    def has_profile(self):
        """
        Checks if the user has an associated profile.
        :return: True if the user has an associated profile, False otherwise.
        """
        try:
            assert self.profile
            return True
        except ObjectDoesNotExist:
            return False

    @property
    def topics_set(self):
        """
        :return: User Topics set.
        """
        return self.topics.all()

    @property
    def topics_count(self):
        """
        :return: User Topics number.
        """
        return self.topics.all().count()

    @property
    def comments_set(self):
        """
        :return: User Comments set.
        """
        return self.comments.all()

    @property
    def comments_set_group_by_book(self):
        """
        :return: User comments set, grouped by book.
            Dictionary in the form {Book: [Comment list]}
        """
        comments = self.comments.all().order_by('-creation_date_time', 'topic__book')

        comments_group_by_book = defaultdict(list)
        for comment in comments:
            comments_group_by_book[comment.topic.book].append(comment)

        return comments_group_by_book

    @property
    def comments_count(self):
        """
        :return: User Comments number.
        """
        return self.comments.all().count()

    @property
    def likes_count(self):
        """
        :return: Number of Likes put by the User.
        """
        return self.likes.all().count()

    @property
    def saved_topics_set(self):
        """
        :return: User saved Topics set, ordered by inverse creation date.
        """
        bookmarks = self.bookmarks.all()
        return Topic.objects.filter(bookmarks__in=bookmarks).order_by('-bookmarks__creation_date_time')

    @property
    def liked_topics_set(self):
        """
        :return: Topics set liked by the User, ordered by inverse creation date.
        """
        likes = self.likes.all()
        return Topic.objects.filter(likes__in=likes).order_by('-likes__creation_date_time')

    @property
    def bookmarks_count(self):
        """
        :return: User Bookmarks number.
        """
        return self.bookmarks.all().count()

    @staticmethod
    def get_popular_by_topics():
        """
        :return: 5 most popular Users based on published Topics.
        """
        return PlatformUser.objects.all().annotate(num_topics=Count('topics')).order_by('-num_topics')\
            .exclude(profile=None)[:5]

    @staticmethod
    def get_popular_by_comments():
        """
        :return: 5 most popular Users based on published Comments.
        """
        return PlatformUser.objects.all().annotate(num_comments=Count('comments')).order_by('-num_comments')\
            .exclude(profile=None)[:5]

    @property
    def get_followed_profiles(self):
        """
        :return: List of Profile followed by the User, ordered by start follow date decreasing.
        """
        return self.followed_profiles.all().order_by('-follower_relations__starting_follow_date_time')

    # def clean(self):
    #     """
    #     Checks that Terms of Service have been accepted. Otherwise it denies User creation.
    #     """
    #     if not self.terms_of_service_acceptance:
    #         raise ValidationError(_('È necessario accettare i termini di servizio per proseguire.'))


class Profile(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    description = models.TextField(max_length=10000, blank=True, null=True)
    picture = models.ImageField(upload_to='profiles/images/%Y/%m/%d',
                                default="profiles/default/default_profile_image.jpg",
                                blank=True, null=True)

    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followed_profiles",
                                       through="FollowRelation")

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="profile")

    def __str__(self):
        return "%s (%s)" % (self.get_name, self.user.username)

    @property
    def get_name(self):
        """
        :return: Complete name.
        """
        return f"{self.first_name} {self.last_name}"

    @property
    def books_count(self):
        """
        :return: Number of books in the User Bookshelf.
        """
        return self.books.all().count()

    @property
    def books_set(self):
        """
        :return: Book list in the User Bookshelf, ordered by:
                    1. Reading end date decreasing
                    2. Reading start date decreasing
                    3. Last update date decreasing
        """
        books = self.books.all()
        return Book.objects.filter(profile_books__in=books).\
            order_by('-profile_books__end_reading_date',
                     '-profile_books__start_reading_date', '-profile_books__last_update_date_time')

    @property
    def books_set_for_shelf(self):
        """
        :return: Book list in the User Bookshelf, excluding those without cover. Results are ordered by:
                    1. Reading end date decreasing
                    2. Reading start date decreasing
                    3. Last update date decreasing
        """
        books = self.books.all().exclude(book__cover_image_file__exact=Book._meta.get_field('cover_image_file').default)
        return Book.objects.filter(profile_books__in=books).\
            order_by('-profile_books__end_reading_date', '-profile_books__start_reading_date',
                     '-profile_books__last_update_date_time')

    @property
    def reading_books_set(self):
        books = self.books.filter(status='READING')
        return Book.objects.filter(profile_books__in=books).order_by('-profile_books__start_reading_date')

    @property
    def read_books_set(self):
        books = self.books.filter(status='READ')
        return Book.objects.filter(profile_books__in=books).order_by('-profile_books__end_reading_date')

    @property
    def must_read_books_set(self):
        books = self.books.filter(status='MUSTREAD')
        return Book.objects.filter(profile_books__in=books).order_by('-profile_books__last_update_date_time')

    def save(self, *args, **kwargs):
        """
        Adjust profile picture size in order to make it a square.
        Sets the default image if no one has been added.
        """
        super().save()
        if self.picture:
            img = Image.open(self.picture.path)
            width, height = img.size

            if width > 300 and height > 300:
                img.thumbnail((width, height))

            if height < width:
                left = (width - height) / 2
                right = (width + height) / 2
                top = 0
                bottom = height
                img = img.crop((left, top, right, bottom))

            elif width < height:
                left = 0
                right = width
                top = 0
                bottom = width
                img = img.crop((left, top, right, bottom))

            if width > 300 and height > 300:
                img.thumbnail((300, 300))

            img.save(self.picture.path)
        else:
            self.picture = self._meta.get_field('picture').get_default()
            self.save()


class FollowRelation(models.Model):
    user_following = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="following_relations",
                                       on_delete=models.CASCADE)
    profile_followed = models.ForeignKey(Profile, related_name="follower_relations", on_delete=models.CASCADE)
    starting_follow_date_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s segue %s" % (self.user_following.username, self.profile_followed.user.username)


class ProfileBook(models.Model):
    READING = 'READING'
    READ = 'READ'
    MUST_READ = 'MUSTREAD'

    BOOK_STATUS_CHOICES = [
        (READING, _("In lettura")),
        (READ, _("Letto")),
        (MUST_READ, _("Da leggere")),
    ]

    profile_owner = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="books")
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="profile_books", null=True, blank=True)
    creation_date_time = models.DateTimeField(auto_now_add=True)
    last_update_date_time = models.DateTimeField(auto_now=True)

    start_reading_date = models.DateField(null=True, blank=True)
    end_reading_date = models.DateField(null=True, blank=True)

    status = models.CharField(max_length=8, choices=BOOK_STATUS_CHOICES, default=READ)
    rating = models.PositiveSmallIntegerField(blank=True, null=True, validators=[MaxValueValidator(100)])

    def __str__(self):
        return "%s - %s" % (self.profile_owner.user.username, self.book.title)

    @property
    def get_verbose_status(self):
        """
        Book state human readable.
        """
        if self.status == 'READ':
            return _("Letto")
        if self.status == 'READING':

user_management/templates/user_management/bookshelf/base_bookshelf_nav.html
{% comment %}
    Base template of Bookshelf navigation pills.
{% endcomment %}

<nav class="nav nav-pills header-tabs flex-sm-row mb-0">
    <a id="reading-link"
       class="flex-sm-fill text-sm-center nav-link active site-btn-outline mr-4 cursor-pointer">
        <div class="d-flex align-items-center">
            <i class="fas fa-book-reader mr-2 nav-link-icon"></i>
            <span class="font-4 nav-link-text">
                In lettura
            </span>
            <span class="font-4">&nbsp;
                {{ profile.reading_books_set.count }}
            </span>
        </div>
    </a>
    <a id="read-link"
       class="flex-sm-fill text-sm-center nav-link mr-4 ml-4 cursor-pointer">
        <div class="d-flex align-items-center">
            <i class="far fa-check-circle mr-2 nav-link-icon"></i>
            <span class="font-4 nav-link-text">
                Letti
            </span>
            <span class="font-4">&nbsp;
                {{ profile.read_books_set.count }}
            </span>
        </div>
    </a>
    <a id="must-read-link"
       class="flex-sm-fill text-sm-center nav-link ml-4 cursor-pointer">
        <div class="d-flex align-items-center">
            <i class="far fa-clock mr-2 nav-link-icon"></i>
            <span class="font-4 nav-link-text">
                Da leggere
            </span>
            <span class="font-4">&nbsp;
                {{ profile.must_read_books_set.count }}
            </span>
        </div>
    </a>
</nav>

user_management/templates/user_management/bookshelf/base_dropdown_bookshefl_choices.html
{% comment %}
    Base template for Bookshelf categories dropdown.
{% endcomment %}

{% if not type == "READING" %}
    <a data-post-id="{{ book.pk }}" class="dropdown-item cursor-pointer {{ action }}-book-reading">
        In lettura &nbsp;&#128214;
    </a>
{% endif %}
{% if not type == "READ" %}
    <a data-post-id="{{ book.pk }}" class="dropdown-item cursor-pointer {{ action }}-book-read">
        Letto &nbsp;<i class="fas fa-check"></i>
    </a>
{% endif %}
{% if not type == "MUSTREAD" %}
    <a data-post-id="{{ book.pk }}" class="dropdown-item cursor-pointer {{ action }}-book-must-read">
        Da leggere &nbsp;&#128355;
    </a>
{% endif %}

user_management/templates/user_management/bookshelf/bookshelf.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% comment %}
    Bookshelf homepage.
{% endcomment %}

{% block title %}{{ block.super }} Bookshelf{% endblock %}

{% block header %}
    <div id="bookshelf-header-background" class="row w-100 d-flex align-items-center justify-content-center shadow">
        <span class="text-white text-center logo-font font-5 display-4 site-big-title">
            {% if request.user == user_for_profile %}
                Bookshelf
            {% else %}
                Bookshelf di {{ user_for_profile.username|truncatechars:40 }}
            {% endif %}
        </span>
    </div>
{% endblock %}

{% block content %}
    <div class="container-fluid site-box p-4 bg-white w-100 shadow">
        <div class="row">
            <div class="col-lg-3 col-12 site-col">
                <div class="media d-flex align-items-center">
                    <a href="{% url 'user_management:view-profile' user_for_profile.pk %}">
                        <img class="rounded-picture-medium align-self-center"
                             src="{{ user_for_profile.profile.picture.url }}">
                    </a>
                    <div class="media-body ml-3 text-muted">
                        <a href="{% url 'user_management:view-profile' user_for_profile.pk %}"
                           class="flat-link font-6 break-word">
                            {{ user_for_profile.profile.user.username|truncatechars:30 }}
                        </a>
                        <br>
                        <span class="font-4 break-word">{{ user_for_profile.profile.get_name|truncatechars:40 }}</span>
                    </div>
                </div>
            </div>
            <div class="site-col col-lg-6 col-12">
                <div class="mb-1">
                    <h6 class="font-5">
                        <a class="site-link break-word" href="{% url 'user_management:view-profile' user_for_profile.pk %}">
                            {% if request.user == user_for_profile %}
                                Profilo
                            {% else %}
                                {{ user_for_profile.username|truncatechars:16 }}
                            {% endif %}
                        </a>
                        &nbsp;>&nbsp;
                        Bookshelf
                    </h6>
                    <h5 class="font-6 mb-3">Bookshelf</h5>
                    {% for book in user_for_profile.profile.books_set_for_shelf|slice:30 %}
                        {% if user_for_profile == user %}
                            <a href="{% url 'view-private-book' book.pk %}" class="no-decoration">
                                <img class="picture-medium" src="{{ book.cover_image_file.url }}" alt="">
                            </a>
                        {% else %}
                            <a href="{% url 'view-public-book' book.pk %}" class="no-decoration">
                                <img class="picture-medium" src="{{ book.cover_image_file.url }}" alt="">
                            </a>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div class="col unnecessary-column"></div>
        </div>
        <div class="d-flex justify-content-center mt-3">
            {% include 'user_management/bookshelf/base_bookshelf_nav.html' with profile=user_for_profile.profile %}
        </div>
    </div>
    {% if request.user == user_for_profile %}
        <div class="container-fluid p-4 mb-2 w-75 mt-4">
            <div class="row d-flex align-items-center justify-content-end">
                <a id="bookshelf-new-book" class="btn site-btn shadow">
                    <i class="fas fa-plus"></i> <span class="font-7"> Nuovo libro</span>
                </a>
            </div>
            <div id="bookshelf-search-book-form" class="row" style="display: none">
                <div class="col site-col d-flex align-items-center">
                    <a id="bookshelf-hide-search" href="#" class="site-blue-text font-7 mr-5">
                        Annulla
                    </a>
                </div>
                <div class="col-lg-9 col-12 site-col d-flex align-items-center justify-content-between">
                    {% crispy form %}
                    <button class="btn btn-transparent small-btn form-control w-auto ml-3"
                            type="submit" form="search-book-crispy-form">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    {% endif %}
    <div id="reading-set" class="mt-3">
        <div class="site-box container-fluid shadow p-4 mb-3 bg-white w-75">
            <div class="d-flex align-items-center justify-content-between">
                <div class="d-flex align-items-center justify-content-start">
                    <h4 class="font-6 ml-3">In lettura</h4>
                    <h5 class="text-muted font-6 ml-3">{{ user_for_profile.profile.reading_books_set.count }}</h5>
                </div>
                {% if request.user == user_for_profile and user_for_profile.profile.reading_books_set|length != 0 %}
                    <a class="site-blue-text font-6 no-decoration mr-3" href="{% url 'user_management:update-reading-books' %}">
                        Modifica
                    </a>
                {% endif %}
            </div>
            <hr>
            {% if user_for_profile.profile.reading_books_set|length != 0 %}
                {% if user_for_profile == user %}
                    {% include 'book_management/books_action_list_view_private_book.html' with books=user_for_profile.profile.reading_books_set %}
                {% else %}
                    {% include 'book_management/books_action_list_view_public_book.html' with books=user_for_profile.profile.reading_books_set %}
                {% endif %}
            {% else %}
                <div class="p-3">
                    <span class="font-5">Ancora nessun libro in lettura</span>
                </div>
            {% endif %}
        </div>
    </div>
    <div id="read-set" class="mt-3" style="display: none">
        <div class="site-box container-fluid shadow p-4 mb-3 bg-white w-75">
            <div class="d-flex align-items-center justify-content-between">
                <div class="d-flex align-items-center justify-content-start">
                    <h4 class="font-6 ml-3">Letti</h4>
                    <h5 class="text-muted font-6 ml-3">{{ user_for_profile.profile.read_books_set.count }}</h5>
                </div>
                {% if request.user == user_for_profile and user_for_profile.profile.read_books_set|length != 0 %}
                    <a class="site-blue-text font-6 no-decoration mr-3" href="{% url 'user_management:update-read-books' %}">
                        Modifica
                    </a>
                {% endif %}
            </div>
            <hr>
            {% if user_for_profile.profile.read_books_set|length != 0 %}
                {% if user_for_profile == user %}
                    {% include 'book_management/books_action_list_view_private_book.html' with books=user_for_profile.profile.read_books_set rating=True %}
                {% else %}
                    {% include 'book_management/books_action_list_view_public_book.html' with books=user_for_profile.profile.read_books_set rating=True %}
                {% endif %}
            {% else %}
                <div class="p-3">
                    <span class="font-5">Ancora nessun libro letto</span>
                </div>
            {% endif %}
        </div>
    </div>
    <div id="must-read-set" class="mt-3" style="display: none">
        <div class="site-box container-fluid shadow p-4 mb-3 bg-white w-75">
            <div class="d-flex align-items-center justify-content-between">
                <div class="d-flex align-items-center justify-content-start">
                    <h4 class="font-6 ml-3">Da leggere</h4>
                    <h5 class="text-muted font-6 ml-3">{{ user_for_profile.profile.must_read_books_set.count }}</h5>
                </div>
                {% if request.user == user_for_profile and user_for_profile.profile.must_read_books_set|length != 0 %}
                    <a class="site-blue-text font-6 no-decoration mr-3" href="{% url 'user_management:update-must-read-books' %}">
                        Modifica
                    </a>
                {% endif %}
            </div>
            <hr>
            {% if user_for_profile.profile.must_read_books_set|length != 0 %}
                {% if user_for_profile == user %}
                    {% include 'book_management/books_action_list_view_private_book.html' with books=user_for_profile.profile.must_read_books_set %}
                {% else %}
                    {% include 'book_management/books_action_list_view_public_book.html' with books=user_for_profile.profile.must_read_books_set %}
                {% endif %}
            {% else %}
                <div class="p-3">
                    <span class="font-5">Ancora nessun libro da leggere</span>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    <script src="{% static 'js/bookshelf.js' %}"></script>
{% endblock %}

user_management/templates/user_management/bookshelf/bookshelf_ajax.html
<script type="text/javascript">
    /**
     * Ajax request to delete a book from the user Bookshelf.
     * success: Calls removeBook to graphically remove the row.
     * @param book_pk Book to delete pk.
     * @param link_clicked User clicked link.
     */
    function ajaxDeleteBook(book_pk, link_clicked) {
        let $row = link_clicked.closest('.bookshelf-element');
        $.ajax({
            type: 'POST',
            url: "{% url 'user_management:ajax-delete-book' %}",
            data: {
                'book_primary_key': book_pk,
            },
            headers:{
                "X-CSRFToken": '{{ csrf_token }}'
            },
            dataType: 'json',
            beforeSend: function() {
                $row.find('.delete-book-icon').tooltip('dispose');
                $row.html('<div class="spinner-border" role="status"><span class="sr-only">Loading...</span></div>');
            },
            success: function(data) {
                bookshelfOperationSuccess(data, $row);
            }
        });
    }

    /**
     * Ajax request to move a book in the user Bookshelf from a category to another.
     * success: Calls removeBook to grephically remove the row.
     * @param book_pk Book to move pk.
     * @param move_to String, it represents the category to which to move the book.
     * @param link_clicked User clicked link.
     */
    function ajaxMoveBook(book_pk, move_to, link_clicked) {
        let $row = link_clicked.closest('.bookshelf-element');
        $.ajax({
            type: 'POST',
            url: "{% url 'user_management:ajax-move-book' %}",
            data: {
                'book_primary_key': book_pk,
                'move_to': move_to,
            },
            headers:{
                "X-CSRFToken": '{{ csrf_token }}'
            },
            dataType: 'json',
            beforeSend: function() {
                $row.html('<div class="spinner-border" role="status"><span class="sr-only">Loading...</span></div>');
            },
            success: function(data) {
                bookshelfOperationSuccess(data, $row);
            }
        });
    }

    /**
     * Ajax request to insert a new book in the Bookshelf.
     * success: Calls removeBook to graphically remove the row.
     * @param book_pk Book to insert pk.
     * @param move_to String, it represents the category to which to move the book.
     * @param link_clicked User clicked link.
     */
    function ajaxNewBook(book_pk, move_to, link_clicked) {
        let $row = link_clicked.closest('.bookshelf-element');
        $.ajax({
            type: 'POST',
            url: "{% url 'user_management:ajax-new-book' %}",
            data: {
                'book_primary_key': book_pk,
                'move_to': move_to,
            },
            headers:{
                "X-CSRFToken": '{{ csrf_token }}'
            },
            dataType: 'json',
            beforeSend: function() {
                $row.html('<div class="spinner-border" role="status"><span class="sr-only">Loading...</span></div>');
            },
            success: function(data) {
                bookshelfOperationSuccess(data, $row);
            }
        });
    }
</script>

user_management/templates/user_management/bookshelf/bookshelf_new_book.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% comment %}
    Page to insert a new book in the Bookshelf.
{% endcomment %}

{% block title %}Bookshelf | Nuovo libro{% endblock %}

{% block content %}
    <div class="container-fluid site-box p-4 bg-white w-100 mb-3 shadow">
        <div class="row">
            <div class="col unnecessary-column"></div>
            <div class="site-col col-lg-6 col-12">
                <div class="mb-5">
                    <h6 class="font-5">
                        <a class="site-link" href="{% url 'user_management:view-profile' user.pk %}">
                            Profilo
                        </a>
                        &nbsp;>&nbsp;
                        <a class="site-link" href="{% url 'user_management:bookshelf' user.pk %}">
                            Bookshelf
                        </a>
                        &nbsp;>&nbsp;
                        Nuovo libro
                    </h6>
                    <h5 class="font-6 mb-0">Nuovo libro</h5>
                    <span class="text-muted font-5 mt-0">
                        Aggiungi libri al tuo bookshelf
                    </span>
                    <div class="mt-3 d-flex justify-content-center align-items-center">
                        {% crispy form %}
                        <button class="btn btn-transparent small-btn form-control w-auto ml-3"
                                type="submit" form="search-book-crispy-form">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
                <div class="search-list-books">
                    {% if books|length_is:0 %}
                        <span class="font-7 site-red-text">Nessun libro trovato.</span>
                        <a href="{% url 'book_management:new-book' %}" class="site-blue-text font-7">
                            Prova a inserirlo tu
                        </a>
                    {% else %}
                        {% include 'user_management/bookshelf/bookshelf_new_book_list.html' %}
                    {% endif %}
                </div>
            </div>
            <div class="col unnecessary-column"></div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    <script src="{% static 'js/update_bookshelf.js' %}"></script>
    {% include 'user_management/bookshelf/bookshelf_ajax.html' %}
{% endblock %}