book_management/urls.py
from book_management import views
from django.urls import path

app_name = 'book_management'

urlpatterns = [
    path('new', views.NewBookView.as_view(), name='new-book'),
    path('ajax-search-book', views.ajax_search_book, name='ajax-search-book'),
]

books_base_folder/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from . import views
from . import settings

urlpatterns = [
    path('grass', views.GrassView.as_view(), name='grass'),
    path('', views.HomepageView.as_view(), name='home'),
    path('search', views.SearchView.as_view(), name='search'),
    path('statistics', views.StatisticsView.as_view(), name='statistics'),
    path('user/', include('user_management.urls')),
    path('books/', include('book_management.urls')),
    path('comments/', include('comment_management.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('view/<int:pk>/public', views.PublicBookPageView.as_view(), name='view-public-book'),
    path('view/<int:pk>/private', views.PrivateBookPageView.as_view(), name='view-private-book'),
    path('notifications', views.NotificationsView.as_view(), name='notifications'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

comment_management/urls.py
from django.urls import path

from comment_management import views

app_name = 'comment_management'

urlpatterns = [
    path('ajax-save-like', views.ajax_save_like, name='ajax-save-like'),
    path('ajax-save-bookmark', views.ajax_save_bookmark, name='ajax-save-bookmark'),
    path('new/topic/<int:pk>', views.NewTopicView.as_view(), name='new-topic'),
    path('update/topic/<int:pk>', views.UpdateTopicView.as_view(), name='update-topic'),
    path('delete/topic/<int:pk>', views.DeleteTopicView.as_view(), name='delete-topic'),
    path('view/topic/<int:pk>', views.TopicPageView.as_view(), name='view-topic'),
    path('delete/comment/<int:pk>', views.DeleteCommentView.as_view(), name='delete-comment'),
]

user_management/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from user_management import views

app_name = 'user_management'

urlpatterns = [
    path('registration', views.UserCreateView.as_view(), name='registration'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/view', views.UserProfileView.as_view(), name='view-profile'),
    path('profile/create', views.CreateProfileView.as_view(), name='create-profile'),
    path('profile/update', views.UpdateProfileView.as_view(), name='update-profile'),
    path('profile/delete', views.DeleteProfileView.as_view(), name='delete-profile'),
    path('delete', views.DeleteUserView.as_view(), name='delete-user'),
    path('profile/settings', views.ProfileSettingsView.as_view(), name='user-settings'),
    path('profile/settings/password', views.UpdatePasswordView.as_view(), name='user-password'),
    path('profile/<int:pk>/bookshelf', views.BookshelfView.as_view(), name='bookshelf'),
    path('profile/bookshelf/new-book', views.BookshelfNewBook.as_view(), name='bookshelf-new-book'),
    path('profile/bookshelf/<int:pk>/update', views.UpdateBookInfo.as_view(), name='bookshelf-update-book'),
    path('profile/bookshelf/reading/update', views.UpdateReadingBooks.as_view(), name='update-reading-books'),
    path('profile/bookshelf/read/update', views.UpdateReadBooks.as_view(), name='update-read-books'),
    path('profile/bookshelf/mustread/update', views.UpdateMustReadBooks.as_view(), name='update-must-read-books'),
    path('profile/following', views.FollowingUsersListView.as_view(), name='following-profiles'),
    path('profile/update/picture', views.UpdateProfilePictureView.as_view(), name='update-profile-picture'),
    path('email/verification_needed', views.EmailVerificationNeededView.as_view(), name='email-verification-needed'),
    path('email/verified', views.EmailVerifiedView.as_view(), name='email-verified'),
    path('report', views.ReportView.as_view(), name='report'),
    path('verify/<str:user_id_b64>/<str:user_token>', views.verify_user_email, name='verify-user-email'),
    path('ajax-save-follow', views.ajax_save_follow, name='ajax-save-follow'),
    path('ajax-check-username-exists', views.ajax_check_username_exists, name='ajax-check-username-exists'),
    path('ajax-delete-book', views.ajax_delete_book, name='ajax-delete-book'),
    path('ajax-move-book', views.ajax_move_book, name='ajax-move-book'),
    path('ajax-new-book', views.ajax_new_book, name='ajax-new-book'),
]

comment_management/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from comment_management.models import Topic, Comment


class NewTopicCrispyForm(forms.ModelForm):
    """
    Form to create a new Topic.

    Fields:
        - title
        - message
    """
    helper = FormHelper()
    helper.form_id = 'new-topic-crispy-form'
    helper.form_method = 'POST'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'mt-5 light-input w-75',
            'placeholder': 'Titolo'
        })

    class Meta:
        model = Topic
        fields = ("title", "message")
        labels = {
            'title': '',
            'message': '',
        }


class UpdateTopicCrispyForm(forms.ModelForm):
    """
    Form to update an existing Topic.

    Fields:
        - title
        - message
    """
    helper = FormHelper()
    helper.form_id = 'update-topic-crispy-form'
    helper.form_method = 'POST'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'light-input',
            'placeholder': 'Titolo'
        })

    class Meta:
        model = Topic
        fields = ('title', 'message')
        labels = {
            'title': 'Titolo',
            'message': 'Messaggio',
        }


class InsertCommentCrispyForm(forms.ModelForm):
    """
    Form to create a new Comment.

    Fields:
        - message
    """
    helper = FormHelper()
    helper.form_id = 'insert-comment-crispy-form'
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Commenta', css_class='btn site-btn'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['message'].widget.attrs.update({
            'id': 'new-comment-field',
            'class': 'w-100 ',
            'placeholder': 'Aggiungi un commento ...',
            'rows': '3',
            'style': 'resize: none;'
        })

    class Meta:
        model = Comment
        fields = {'message'}
        labels = {
            'message': '',
        }

comment_management/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, DeleteView, ListView, UpdateView, View
from django.views.generic.detail import SingleObjectMixin

from book_management.models import Book
from comment_management.decorators import topic_owner_only, comment_owner_only
from comment_management.forms import NewTopicCrispyForm, UpdateTopicCrispyForm, InsertCommentCrispyForm
from comment_management.models import Comment, Like, Bookmark, Topic


@login_required
@require_POST
@csrf_protect
def ajax_save_like(request):
    """
    Ajax called function to save a Like.
    It receives a Topic pk. It checks if a Like for the request user on the Topic already exists:
        - if so, it takes it off
        - otherwise, it adds it
    :return:
        - selected: boolean value, True if the Like has been added, False otherwise
        - likes_count: number of likes of the Topic after the operation
    """
    topic_id = request.POST.get('topic_primary_key')
    selected = False

    if Like.objects.filter(topic=topic_id, user_owner_id=request.user.pk).exists():
        Like.objects.get(topic=topic_id, user_owner_id=request.user.pk).delete()
    else:
        topic_obj = Topic.objects.get(pk=topic_id)
        like = Like(user_owner_id=request.user.pk, topic=topic_obj)
        like.save()
        selected = True

    likes_count = Like.objects.filter(topic=topic_id).count()

    data = {
        'selected': selected,
        'likes_count': likes_count
    }

    return JsonResponse(data)


@login_required
@require_POST
@csrf_protect
def ajax_save_bookmark(request):
    """
    Ajax called function to save a Bookmark.
    It receives a Topic pk. It checks if a Bookmark for the request user on the Topic already exists:
        - if so, it takes it off
        - otherwise, it adds it
     :return: boolean value, True if the Bookmark has been added, False otherwise.
     """
    topic_id = request.POST.get('topic_primary_key')
    selected = False

    if Bookmark.objects.filter(topic=topic_id, user_owner_id=request.user.pk).exists():
        Bookmark.objects.get(topic=topic_id, user_owner_id=request.user.pk).delete()
    else:
        topic_obj = Topic.objects.get(pk=topic_id)
        bookmark = Bookmark(user_owner_id=request.user.pk, topic=topic_obj)
        bookmark.save()
        selected = True

    data = {
        'selected': selected
    }

    return JsonResponse(data)


class NewTopicView(LoginRequiredMixin, CreateView):
    """
    Topic CreateView.
    It contains NewTopicCrispyForm.
    """
    form_class = NewTopicCrispyForm
    template_name = 'comment_management/new_topic.html'

    def get_context_data(self, **kwargs):
        """
        Retrieves book data on which you are trying to post a Topic.
        :return: Book object.
        """
        context = super(NewTopicView, self).get_context_data(**kwargs)
        context['book'] = Book.objects.get(pk=self.kwargs['pk'])

        return context

    def form_valid(self, form):
        """
        Collects additional data needed to complete the operation.
        """
        self.object = form.save(commit=False)
        self.object.user_owner_id = self.request.user.pk
        self.object.book_id = self.kwargs['pk']
        self.object.save()

        return super().form_valid(form)

    def get_success_url(self):
        """
        :return: redirect towards the page 'view-book' of the book related to the just added Topic.
        """
        return reverse_lazy('view-public-book', kwargs={'pk': self.kwargs['pk']})


@method_decorator(topic_owner_only, name='dispatch')
class UpdateTopicView(LoginRequiredMixin, UpdateView):
    """
    Topic UpdateView.
    It contains UpdateTopicCrispyForm.
    """
    model = Topic
    form_class = UpdateTopicCrispyForm
    template_name = "comment_management/update_topic.html"

    def get_context_data(self, **kwargs):
        """
        Retrieves book data on which the Topic is published.
        :return: Book object.
        """
        context = super(UpdateTopicView, self).get_context_data(**kwargs)
        book_pk = Topic.objects.get(pk=self.kwargs['pk']).book_id
        context['book'] = Book.objects.get(pk=book_pk)

        return context

    def get_success_url(self):
        """
        :return: redirect towards the page 'view-topic' of the updated Topic.
        """
        return reverse_lazy('comment_management:view-topic', kwargs={'pk': self.kwargs['pk']})


@method_decorator(topic_owner_only, name='dispatch')
class DeleteTopicView(LoginRequiredMixin, DeleteView):
    """
    Topic DeleteView.
    """
    model = Topic
    template_name = 'comment_management/delete_topic.html'

    def get_success_url(self):
        """
        :return: redirect towards the page 'view-profile' of the requesting user.
        """
        return reverse_lazy('user_management:view-profile', kwargs={'pk': self.request.user.pk})


class TopicNewComment(LoginRequiredMixin, CreateView):
    """
    Comment CreateView.
    It contains InsertCommentCrispyForm.
    """
    form_class = InsertCommentCrispyForm

    def form_valid(self, form):
        """
        Collects additional data needed to complete the operation.
        """
        self.object = form.save(commit=False)
        self.object.user_owner_id = self.request.user.pk
        self.object.topic_id = self.kwargs['pk']
        self.object.save()

        return super().form_valid(form)

    def get_success_url(self):
        """
        :return: redirect towards the page 'view-topic' of the comment related Topic.
        """
        return reverse_lazy('comment_management:view-topic', kwargs={'pk': self.kwargs['pk']})


class CommentsList(SingleObjectMixin, ListView):
    """
    Comment ListView.
    """
    template_name = 'comment_management/view_topic.html'
    model = Comment

    def get(self, request, *args, **kwargs):
        """
        Retrieves Topic object.
        :return: Topic object.
        """
        self.object = Topic.objects.get(pk=self.kwargs['pk'])
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """
        Saves Topic object and form in the context.
        """
        context = super(CommentsList, self).get_context_data(**kwargs)
        context['topic'] = self.object
        context['form'] = InsertCommentCrispyForm
        return context

    def get_queryset(self):
        """
        Retrieves Topic comment list.
        :return: Comment object list.
        """
        return self.object.comments_set


class TopicPageView(View):
    """
    Topic View, containing the Topic, the related comment list and the form to add a new comment.
    """
    def get(self, request, *args, **kwargs):
        view = CommentsList.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = TopicNewComment.as_view()
        return view(request, *args, **kwargs)


@method_decorator(comment_owner_only, name='dispatch')
class DeleteCommentView(LoginRequiredMixin, DeleteView):
    """
    Comment DeleteView.
    """
    model = Comment
    template_name = 'comment_management/delete_comment.html'

    def get_context_data(self, **kwargs):
        """
        Saves Topic object of the comment you are trying to delete in the context.
        :return: Topic object.
        """
        context = super(DeleteCommentView, self).get_context_data(**kwargs)
        context['topic'] = self.object.topic
        return context

    def get_success_url(self):
        """
        :return: redirect towards the page 'view-topic' of the Topic related to the just deleted comment.
        """
        return reverse_lazy('comment_management:view-topic', kwargs={'pk': self.object.topic_id})

comment_management/templates/comment_management/base_comment.html
{% comment %}
    Base template for viewing a Comment.
{% endcomment %}

<div class="row">
    <div class="site-col col-12 d-flex justify-content-between">
        <div>
            {% if not is_delete %}
                <div class="media">
                    {% if comment.user_owner.has_profile and comment.user_owner.profile.picture %}
                        <a href="{% url 'user_management:view-profile' comment.user_owner.pk %}">
                            <img src="{{ comment.user_owner.profile.picture.url }}"
                                 class="align-self-center rounded-picture-small">
                        </a>
                    {% endif %}
                    <div class="media-body ml-3">
                        <a class="no-decoration flat-link" href="{% url 'user_management:view-profile' comment.user_owner.pk %}">
                            <span class="text-muted font-6 mr-3">{{ comment.user_owner.username }}</span>
                        </a> <br>
                        <span class="font-4 font-size-90 text-muted">{{ comment.creation_date_time|timesince }} fa</span>
                    </div>
                </div>
            {% endif %}
{#            <div class="mt-3">#}
{#                {% include 'comment_management/base_truncated_text.html' with text=comment.message chars=1100 %}#}
{#            </div>#}
        </div>
        <div>
            {% if not is_delete %}
                <i class="fas fa-ellipsis-h site-icon"
                   data-toggle="dropdown"></i>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left">
                    {% if comment.user_owner != user %}
                        <a class="dropdown-item cursor-pointer" href="{% url 'user_management:report' %}">
                            Report &nbsp;<i class="fas fa-bullhorn"></i>
                        </a>
                    {% else %}
                        <a class="dropdown-item cursor-pointer"
                           href="{% url 'comment_management:delete-comment' comment.pk %}"> Elimina</a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
</div>
<div class="row mt-lg-3 mr-lg-3">
    <div class="col d-flex justify-content-between align-items-end">
        {% include 'comment_management/base_truncated_text.html' with text=comment.message chars=1100 %}
    </div>
{#    <div class="col-auto d-flex justify-content-end align-items-end">#}
{#         <i class="far fa-heart"></i>#}
{#    </div>#}
</div>
{% if is_profile %}
    <div class="row">
        <div class="col site-col mt-3">
            <a class="site-link-light link-decorated" href="{% url 'comment_management:view-topic' topic.pk %}">
                <span class="font-5"> vedi Topic </span>
            </a>
        </div>
    </div>
{% endif %}

comment_management/templates/comment_management/base_topic.html
{% load comment_filters %}
{% load static %}

{% comment %}
    Base template for viewing a Topic.
{% endcomment %}

<div class="row comment-row">
    {% if not is_delete %}
        <div class="site-col col">
            <div class="media">
                {% if topic.user_owner.has_profile and topic.user_owner.profile.picture %}
                    <a href="{% url 'user_management:view-profile' topic.user_owner.pk %}">
                        <img src="{{ topic.user_owner.profile.picture.url }}"
                             class="align-self-center rounded-picture-medium" alt="">
                    </a>
                {% endif %}
                <div class="sm-only text-muted media-body ml-3">
                    <a class="no-decoration flat-link" href="{% url 'user_management:view-profile' topic.user_owner.pk %}">
                        <span class="font-7 break-word">{{ topic.user_owner.username }}</span>
                    </a>
                    <br>
                    {% if topic.user_owner.has_profile %}
                        <span class="font-4">{{ topic.user_owner.profile.get_name }}</span>
                    {% endif %}
                </div>
            </div>

        </div>
    {% endif %}
    <div class="col-xl-9 col-lg-6 col-12 d-flex justify-content-between">
        <div>
            <div>
                <span class="font-4 text-muted">Pubblicato {{ topic.creation_date_time|timesince }} fa</span>
                {% if show_book %}
                    <a class="site-link-light link-decorated" href="{% url 'view-public-book' book.pk %}">
                        <span class="font-5">
                            in {{ book.title|truncatewords:6 }} di {{ book.authors_str|truncatewords:5 }}
                        </span>
                    </a>
                {% endif %}
            </div>
            <h5 class="font-7 break-word">{{ topic.title }}</h5>

        </div>
        {% if not is_delete %}
            <div>
                <i class="fas fa-ellipsis-h site-small-icon"
                   data-toggle="dropdown"></i>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left">
                    {% if topic.user_owner == user %}
                        <a class="dropdown-item cursor-pointer"
                           href="{% url 'comment_management:update-topic' topic.pk %}">
                            <i class="fas fa-pencil-alt mr-3"></i>Modifica
                        </a>
                        <a class="dropdown-item cursor-pointer site-red-text dropdown-item-red"
                           href="{% url 'comment_management:delete-topic' topic.pk %}">
                            <i class="fas fa-trash-alt mr-3"></i>Elimina
                        </a>
                    {% else %}
                        <a class="dropdown-item cursor-pointer" href="{% url 'user_management:report' %}">
                            Report &nbsp;<i class="fas fa-bullhorn"></i>
                        </a>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    </div>
    {% if not is_delete %}
        <div class="col unnecessary-column"></div>
    {% endif %}
</div>

<div class="row comment-row mt-lg-3">
    {% if not is_delete %}
        <div class="col site-col">
            <div class="lg-only text-muted">
                <a class="no-decoration flat-link" href="{% url 'user_management:view-profile' topic.user_owner.pk %}">
                    <span class="font-7 break-word">{{ topic.user_owner.username }}</span>
                </a>
                <br>
                {% if topic.user_owner.has_profile %}
                    <span class="font-4">{{ topic.user_owner.profile.get_name }}</span>
                {% endif %}
            </div>
        </div>
    {% endif %}
    <div class="site-col col-xl-9 col-lg-6 col-12">
        {% include 'comment_management/base_truncated_text.html' with text=topic.message html=True chars=1100 %}
    </div>
    {% if not is_delete %}
        <div class="col unnecessary-column"></div>
    {% endif %}
</div>

<div class="row comment-row mt-3 d-flex align-items-center">
    {% if not is_delete %}
        <div class="col unnecessary-column"></div>
    {% endif %}
    <div class="site-col col-xl-9 col-lg-6 col-12">
        <span class="text-muted font-5">
            <span class="number-of-likes">{{ topic.likes_count }}</span> Mi piace,
            {% with comments_count=topic.comments_count %}
                {{ comments_count }}
                <a class="flat-link" href="{% url 'comment_management:view-topic' topic.pk %}">
                {% if comments_count == 1 %}
                    Commento
                {% else %}
                    Commenti
                {% endif %}
            </a>
            {% endwith %}
        </span>
    </div>
    {% if not is_delete %}
        <div class="col d-flex align-items-center justify-content-between">
            <i data-post-id="{{ topic.pk }}" class="far fa-heart site-md-icon like-icon
                {% if topic|user_likes_topic:user %}
                    like-selected
                {% else %}
                    like-deselected
                {% endif %}
                " data-toggle="tooltip" data-placement="top" title="Mi piace"></i>
            <i data-post-id="{{ topic.pk }}" class="far fa-bookmark site-md-icon bookmark-icon
                     {% if topic|user_saved_topic:user %}
                        bookmark-selected
                     {% else %}
                        bookmark-deselected
                     {% endif %}
                    " data-toggle="tooltip" data-placement="top" title="Salva"></i>
            {% if not is_comment %}
                <a href="{% url 'comment_management:view-topic' topic.pk %}" class="site-link">
                    <i class="far fa-comment site-md-icon add-comment-icon"
                       data-toggle="tooltip" data-placement="top" title="Commenta"></i>
                </a>
            {% endif %}
        </div>
    {% endif %}
</div>

comment_management/templates/comment_management/base_topic_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load book_filters %}

{% comment %}
    Base template with a Topic form.
{% endcomment %}

{% block content %}
    <div class="container-fluid mb-3 w-auto">
        <div class="row">
            <div class="site-col col-lg-9 col-12 site-box bg-white shadow p-4">
                <div class="mb-4">
                    <h6 class="font-5">{% block topic_form_path %}{% endblock %}</h6>
                    <h5 class="font-6 mb-0">{% block topic_form_title %}{% endblock %}</h5>
                    <span class="text-muted font-5 mt-0">{% block topic_form_subtitle %}{% endblock %}</span>
                </div>
                {% crispy form %}
                <div class="d-flex column-flex align-items-start mt-5">
                    <div class="d-flex align-items-center justify-content-between">
                        <input class="btn site-btn w-100" type="submit"
                               form="{% block submit_button_form_id %}{% endblock %}"
                               value="{% block submit_button_value %}{% endblock %}">
                        <a class="site-link font-6 ml-3" href="{% block cancel_button_url %}{% endblock %}">
                            Annulla
                        </a>
                    </div>
                </div>
            </div>
            <div class="site-col col site-box bg-white shadow p-5 ml-3">
                 <div class="d-flex justify-content-center mb-4">
                    <a href="{% url 'view-public-book' book.pk %}" class="no-decoration">
                        <img src="{{ book.cover_image_file.url }}" class="img-fluid cover-img picture-big" alt="">
                    </a>
                </div>
                {% include 'book_management/base_book_metadata_column.html' %}
                <hr>
                <div class="row d-flex align-items-center justify-content-between column-flex mb-4">
                    {% if user.has_profile %}
                        {% if book|user_saved_book:user %}
                            {% if book|user_rated_book:user %}
                                <h5 class="font-7 mb-2">Il tuo voto</h5>
                                {% with vote=book|get_user_book_rating:user %}
                                    {% include 'base_progress_bar.html' with progress_container_custom_class='w-75' %}
                                {% endwith %}
                            {% endif %}
                        {% endif %}
                    {% endif %}
                </div>
                <div class="row d-flex align-items-center justify-content-between column-flex mb-3">
                    {% with vote=book.average_rating %}
                        {% if vote is None %}
                            <h5 class="font-7">Ancora nessun voto</h5>
                        {% else %}
                            <h5 class="font-7 mb-0">Valutazione media</h5>
                            <span class="font-6 text-muted mb-2">
                                {{ book.number_of_ratings }}
                                {% if book.number_of_ratings == 1 %}voto{% else %}voti{% endif %}
                            </span>
                            {% include 'base_progress_bar.html' with progress_container_custom_class='w-75'%}
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

comment_management/templates/comment_management/base_truncated_text.html
{% load comment_filters %}

{% comment %}
    Base template for viewing a truncated text, with buttons to view more or less text.
{% endcomment %}

<div class="text-justify site-text break-word text-box">
    {% if html %}
        <span class="text-message font-4">{{ text|truncate_html_chars:chars|safe }}</span>
    {% else %}
        <span class="text-message font-4">{{ text|truncatechars:chars }}</span>
    {% endif %}
    {% if text|length > chars %}
        <br>
        <a class="site-blue-text font-6 cursor-pointer text-show-more">Leggi tutto</a>
        <a class="site-blue-text font-6 cursor-pointer text-show-less" style="display:none;">Mostra meno</a>
        <span class="text-hidden-message" style="display: none">
            {{ text }}
        </span>
    {% endif %}
</div>

comment_management/templates/comment_management/delete_comment.html
{% extends 'base_delete.html' %}
{% load static %}

{% comment %}
    Comment removal page.
{% endcomment %}

{% block title %}{{ block.super }} Eliminazione commento{% endblock %}

{% block delete_page_path %}
    <a class="site-link" href="{% url 'view-public-book' topic.book.pk %}">{{ topic.book.title|truncatewords:6 }}</a>
    &nbsp;>&nbsp;
    <a class="site-link" href="{% url 'comment_management:view-topic' topic.pk %}">Topic</a>
    &nbsp;>&nbsp;
    Commento
    &nbsp;>&nbsp;
    Elimina commento
{% endblock %}

{% block delete_object_title %}Elimina il tuo commento{% endblock %}
{% block delete_object_subtitle %}Informazioni che verranno perse definitivamente{% endblock %}

{% block delete_object_information %}
    {% include 'comment_management/base_comment.html' with comment=object is_delete=True %}
{% endblock %}
{% block cancel_button_url %}{% url 'comment_management:view-topic' topic.pk %}{% endblock %}

{% block extra_javascript %}
    <script src="{% static 'js/base_topic.js' %}"></script>
    <script src="{% static 'js/show_more_less.js' %}"></script>
{% endblock %}

comment_management/templates/comment_management/topic_ajax.html
<script type="text/javascript">
    /**
     * Ajax request to save a user Like.
     * success: Calls the function fillLike() to manage the icon.
     * @param topic_ppk Primary key of the Topic on which the Like button has been pressed.
     * @param icon_clicked Like icon clicked by the user.
     *
     */
    function ajaxSaveLike(topic_pk, icon_clicked) {
        $.ajax({
            type: 'POST',
            url: "{% url 'comment_management:ajax-save-like' %}",
            data: {
                'topic_primary_key': topic_pk,
            },
            headers:{
                "X-CSRFToken": '{{ csrf_token }}'
            },
            dataType: 'json',
            beforeSend: function() {
            },
            complete: function() {
            },
            success: function(data) {
                fillLike(data, icon_clicked);
            }
        });
    }

    /**
     * Ajax request to save a bookmark.
     * success: Calls the function fillBookmark() to manage the icon.
     * @param topic_pk Primary key of the Topic on which the Bookmark button hase been pressed.
     * @param icon_clicked Bookmark icon clicked by the user.
     *
     */
    function ajaxSaveBookmark(topic_pk, icon_clicked) {
        $.ajax({
            type: 'POST',
            url: "{% url 'comment_management:ajax-save-bookmark' %}",
            data: {
                'topic_primary_key': topic_pk,
            },
            headers:{
                "X-CSRFToken": '{{ csrf_token }}'
            },
            dataType: 'json',
            beforeSend: function() {
            },
            complete: function() {
            },
            success: function(data) {
                fillBookmark(data, icon_clicked);
            }
        });
    }
</script>