book_management/urls.py
from book_management import views
from django.urls import path

app_name = 'book_management'

urlpatterns = [
    path('new', views.NewBookView.as_view(), name='new-book'),
    path('ajax-search-book', views.ajax_search_book, name='ajax-search-book'),
]

books_base_folder/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from . import views
from . import settings

urlpatterns = [
    path('grass', views.GrassView.as_view(), name='grass'),
    path('', views.HomepageView.as_view(), name='home'),
    path('search', views.SearchView.as_view(), name='search'),
    path('statistics', views.StatisticsView.as_view(), name='statistics'),
    path('user/', include('user_management.urls')),
    path('books/', include('book_management.urls')),
    path('comments/', include('comment_management.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('view/<int:pk>/public', views.PublicBookPageView.as_view(), name='view-public-book'),
    path('view/<int:pk>/private', views.PrivateBookPageView.as_view(), name='view-private-book'),
    path('notifications', views.NotificationsView.as_view(), name='notifications'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

comment_management/urls.py
from django.urls import path

from comment_management import views

app_name = 'comment_management'

urlpatterns = [
    path('ajax-save-like', views.ajax_save_like, name='ajax-save-like'),
    path('ajax-save-bookmark', views.ajax_save_bookmark, name='ajax-save-bookmark'),
    path('new/topic/<int:pk>', views.NewTopicView.as_view(), name='new-topic'),
    path('update/topic/<int:pk>', views.UpdateTopicView.as_view(), name='update-topic'),
    path('delete/topic/<int:pk>', views.DeleteTopicView.as_view(), name='delete-topic'),
    path('view/topic/<int:pk>', views.TopicPageView.as_view(), name='view-topic'),
    path('delete/comment/<int:pk>', views.DeleteCommentView.as_view(), name='delete-comment'),
]

user_management/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from user_management import views

app_name = 'user_management'

urlpatterns = [
    path('registration', views.UserCreateView.as_view(), name='registration'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/view', views.UserProfileView.as_view(), name='view-profile'),
    path('profile/create', views.CreateProfileView.as_view(), name='create-profile'),
    path('profile/update', views.UpdateProfileView.as_view(), name='update-profile'),
    path('profile/delete', views.DeleteProfileView.as_view(), name='delete-profile'),
    path('delete', views.DeleteUserView.as_view(), name='delete-user'),
    path('profile/settings', views.ProfileSettingsView.as_view(), name='user-settings'),
    path('profile/settings/password', views.UpdatePasswordView.as_view(), name='user-password'),
    path('profile/<int:pk>/bookshelf', views.BookshelfView.as_view(), name='bookshelf'),
    path('profile/bookshelf/new-book', views.BookshelfNewBook.as_view(), name='bookshelf-new-book'),
    path('profile/bookshelf/<int:pk>/update', views.UpdateBookInfo.as_view(), name='bookshelf-update-book'),
    path('profile/bookshelf/reading/update', views.UpdateReadingBooks.as_view(), name='update-reading-books'),
    path('profile/bookshelf/read/update', views.UpdateReadBooks.as_view(), name='update-read-books'),
    path('profile/bookshelf/mustread/update', views.UpdateMustReadBooks.as_view(), name='update-must-read-books'),
    path('profile/following', views.FollowingUsersListView.as_view(), name='following-profiles'),
    path('profile/update/picture', views.UpdateProfilePictureView.as_view(), name='update-profile-picture'),
    path('email/verification_needed', views.EmailVerificationNeededView.as_view(), name='email-verification-needed'),
    path('email/verified', views.EmailVerifiedView.as_view(), name='email-verified'),
    path('report', views.ReportView.as_view(), name='report'),
    path('verify/<str:user_id_b64>/<str:user_token>', views.verify_user_email, name='verify-user-email'),
    path('ajax-save-follow', views.ajax_save_follow, name='ajax-save-follow'),
    path('ajax-check-username-exists', views.ajax_check_username_exists, name='ajax-check-username-exists'),
    path('ajax-delete-book', views.ajax_delete_book, name='ajax-delete-book'),
    path('ajax-move-book', views.ajax_move_book, name='ajax-move-book'),
    path('ajax-new-book', views.ajax_new_book, name='ajax-new-book'),
]

templates/base.html
{% comment %}
    Application base template.
{% endcomment %}

{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
          crossorigin="anonymous">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;500;600;700;900&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bungee+Shade&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.10/css/bootstrap-select.min.css"
          integrity="sha256-jwJEU4p1YdtymLFwAjYfam5Pj5NOnylms63k7LYQ9Jk=" crossorigin="anonymous" />
    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'img/camp-favicon.png' %}">


    <link rel="stylesheet"
          href="{% static 'css/style.css' %}">
    <link rel="stylesheet"
          href="{% static 'css/media-queries.css' %}">
    {% block extra_css %} {% endblock %}

    <title>{% block title %}Bookcamp |{% endblock %}</title>
</head>

<body>
{% url 'user_management:login' as login_url %}
{% url 'user_management:registration' as registration_url %}
{% if not request.get_full_path == login_url and not request.get_full_path == registration_url %}
    {% include 'navbar.html' %}
{% endif %}

{# Block to extend if you have to create a full width header section at the top of the page #}
{% block header %}{% endblock %}

<div id="site-main-page" class="container-fluid mt-n1 mt-md-3">
    {% block content %}
    {% endblock %}
</div>

{#{% include 'footer.html' %}#}

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.10/js/bootstrap-select.js"
        integrity="sha256-GwAMtRKq8ocZyBdgm1wX+tzd2/nDbb2UGulIdqOItiU=" crossorigin="anonymous"></script>

<!-- SweetAlert 2 JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

<!-- Optional JavaScript -->
<script src="{% static 'js/jQuery_blockUI.js' %}"></script>
<script src="{% static 'js/base.js' %}"></script>
{% block extra_javascript %}{% endblock %}
</body>
</html>

templates/base_list.html
{% load static %}

{% comment %}
    Base template for list of elements.
{% endcomment %}

{% block content %}
    {% block list_prev %} {% endblock %}

    <div class="list-group list-group-flush">
        {% block list_content %} {% endblock %}
    </div>

    {% block list_after %} {% endblock %}
{% endblock %}

templates/navbar.html
{% load static %}

{% comment %}
    Navbar.
{% endcomment %}

<nav id="site-navbar" class="navbar navbar-dark navbar-expand-lg sticky-top py-1 font-5">
    <a href="{% url 'home' %}">
        <span class="navbar-brand navbar-text mb-0 h1 logo-font">Bookcamp</span>
    </a>
    {#    <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"#}
    {#            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
    {#        <span class="navbar-toggler-icon"></span>#}
    {#    </button>#}

    <div class="burger mr-2" style="display: none">
        <div class="line1"></div>
        <div class="line2"></div>
        <div class="line3"></div>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav d-flex align-items-center justify-content-between w-50 ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link navbar-text" href="{% url 'book_management:new-book' %}">Nuovo</a>
                </li>
            {% endif %}
            <li class="nav-item active">
                <a class="nav-link navbar-text" href="{% url 'search' %}">Cerca</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link navbar-text" href="{% url 'statistics' %}">Statistiche globali</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link navbar-text font-7 letter-spacing-1" href="{% url 'grass' %}">GRASS</a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto d-flex align-items-center">
            {% if user.is_authenticated %}
                {% if user.has_profile %}
                    <li class="nav-item active">
                        <a class="nav-link navbar-text" href="{% url 'notifications' %}">
                            <i class="fas fa-bell site-small-icon white-icon d-flex align-items-center"></i>
                        </a>
                    </li>
                    <li class="nav-item active break-word">
                        <a class="ml-lg-2 navbar-text" href="{% url 'user_management:view-profile' user.pk %}"
                           role="button">
                            <img src="{{ user.profile.picture.url }}" class="rounded-picture-xs no-decoration" alt="">
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item active break-word">
                        <a class="ml-lg-2 navbar-text" href="{% url 'user_management:view-profile' user.pk %}"
                           role="button">
                            {{ user.username|truncatechars:30 }}
                        </a>
                    </li>
                {% endif %}
            {% else %}
                <li class="nav-item active">
                    <a class="ml-lg-2 navbar-text" href="{% url 'user_management:login' %}"
                       role="button">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/search_page.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% comment %}
    Search engine page.
{% endcomment %}

{% block extra_css %}
    {% if books is None %}
        <style type="text/css">
            html,body {
                height: 100%;
                overflow: hidden;
            }
        </style>
    {% endif %}
{% endblock %}

{% block title %}{{ block.super }} Cerca{% endblock %}

{% block header %}
    {% if books is None %}
        <div id="book-search-background-no-books-found"
              class="row w-100 d-flex align-items-center justify-content-center column-flex">
    {% else %}
        <div id="book-search-background"
             class="row w-100 d-flex align-items-center justify-content-center column-flex shadow">
    {% endif %}
        <div class="row">
            <span class="text-white text-center logo-font font-5 display-4 site-big-title">Cosa stai cercando?</span>
        </div>
        <div class="row mt-4 w-100 d-flex justify-content-center">
            <div class="col unnecessary-column"></div>
            <div class="col-lg-6 col-12 site-col d-flex justify-content-center">
                    {% crispy form %}
                    <button class="btn btn-transparent small-btn form-control w-auto" type="submit" form="search-crispy-form">
                        <i class="fas fa-search white-icon"></i>
                    </button>
            </div>
            <div class="col unnecessary-column"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    {% if books.count > 0 or profiles.count > 0 %}
        <div class="container-fluid site-box p-2 mb-3 bg-white w-75 shadow">
            <div class="row">
                <div class="col unnecessary-column"></div>
                <div class="col-lg-6 col-12 site-attached-col d-flex align-items-center justify-content-center mt-3 ml-3">
                    <h3 class="font-6 text-center">Risultati della ricerca</h3>
                </div>
                <div class="col unnecessary-column"></div>
            </div>

            <nav class="nav nav-pills header-tabs flex-sm-row mt-4 mb-2">
                <a id="search-header-libri"
                   class="flex-sm-fill text-sm-center nav-link active site-btn-outline ml-5 mr-5 cursor-pointer">
                    <span class="font-4">
                        Libri {{ books.count }}
                    </span>
                </a>
                <a id="search-header-utenti"
                   class="flex-sm-fill text-sm-center nav-link mr-5 ml-5 cursor-pointer">
                    <span class="font-4">
                        Utenti {{ profiles.count }}
                    </span>
                </a>
            </nav>
            <div class="search-list-books">
                {% include 'book_management/books_action_list_view_public_book.html' with top_badge=True %}
            </div>
            <div class="search-list-users" style="display: none;">
                {% include 'user_management/base_profiles_list.html' %}
            </div>
         </div>
    {% else %}
        <h3 class="font-7 d-flex justify-content-center">Nessun risultato corrisponde alla tua ricerca</h3>
        <h5 class="font-7 text-muted d-flex justify-content-center">Prova con qualcos'altro, oppure &nbsp;
            <a class="site-blue-text font-7" href="{% url 'book_management:new-book' %}">inserisci un nuovo libro</a>
        </h5>
    {% endif %}
{% endblock %}

{% block extra_javascript %}
    <script src="{% static 'js/search.js' %}"></script>
{% endblock %}

templates/view_private_book.html
{% extends 'base.html' %}
{% load book_filters %}

{% comment %}
    Book private information page.
{% endcomment %}

{% block title %}{{ block.super }} {{ book.title }} di {{ user.username }}{% endblock %}

{% block header %}
    <div id="view-private-book-header-background"
         class="row w-100 d-flex align-items-center justify-content-center shadow">
        <span class="text-white text-center logo-font font-5 display-4 site-big-title p-2">
          Informazioni private del libro
        </span>
    </div>
{% endblock %}

{% block content %}
    <div class="container-fluid mb-3 w-auto site-attached-col">
        <div class="row">
            <div class="site-col site-box shadow col-lg-9 col-12 p-4 bg-white">
                <div class="row">
                    <div class="col site-col">
                        <h6 class="font-5">
                            <a class="site-link" href="{% url 'user_management:view-profile' user.pk %}">
                                Profilo
                            </a>
                            &nbsp;>&nbsp;
                            <a href="{% url 'user_management:bookshelf' user.pk %}" class="site-link">
                                Bookshelf
                            </a>
                            &nbsp;>&nbsp;
                            Informazioni private libro
                        </h6>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-lg col-12 site-col">
                        {% if book.title %}
                            <h2 class="font-7">{{ book.title }}</h2>
                        {% endif %}
                        {% if book.authors_count > 0 %}
                            <h5 class="font-4 text-muted">di {{ book.authors_str }}</h5>
                        {% endif %}
                        <h6 class="font-6 text-success mb-0">
                            <i class="fas fa-check"></i> &nbsp;{{ book|get_user_book_status:user }}
                        </h6>
                    </div>
                    <div class="col-lg-auto col-12 site-col media d-flex align-items-start">
                        <div class="media-body mr-3 text-muted text-right">
                            <a href="{% url 'user_management:view-profile' user.pk %}"
                               class="flat-link font-6 break-word">
                                {{ user.profile.user.username|truncatechars:30 }}
                            </a>
                            <br>
                            <span class="font-4 break-word">{{ user.profile.get_name|truncatechars:40 }}</span>
                        </div>
                        <a href="{% url 'user_management:view-profile' user.pk %}">
                            <img class="rounded-picture-medium align-self-center" alt=""
                                 src="{{ user.profile.picture.url }}">
                        </a>
                    </div>
                </div>
                <hr>
                <div class="row mt-2">
                    <div class="col-12  d-flex justify-content-end">
                        <i class="fas fa-ellipsis-h site-small-icon"
                           data-toggle="dropdown"></i>
                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left">
                            <a class="dropdown-item cursor-pointer"
                               href="{% url 'user_management:bookshelf-update-book' book.pk %}">Modifica</a>
                        </div>
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-lg-12 col-12 site-col">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h5 class="font-6">&#128198;&nbsp;Inserito</h5>
                            <span class="font-5 text-muted text-right">{{ profile_book.creation_date_time|date }}</span>
                        </div>
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h5 class="font-6">&#128198;&nbsp;Iniziato a leggere</h5>
                            <span class="font-5 text-muted text-right">
                                {% if profile_book.start_reading_date %}
                                    {{ profile_book.start_reading_date }}
                                {% else %}
                                    -
                                {% endif %}
                            </span>
                        </div>
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h5 class="font-6">&#128198;&nbsp;Finito di leggere</h5>
                            <span class="font-5 text-muted text-right">
                                {% if profile_book.end_reading_date %}
                                    {{ profile_book.end_reading_date }}
                                {% else %}
                                    -
                                {% endif %}
                            </span>
                        </div>
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h5 class="font-6"><i class="far fa-star site-yellow-text"></i>&nbsp;Voto</h5>
                            {% if book|user_rated_book:user %}
                                {% with vote=book|get_user_book_rating:user %}
                                    {% include 'base_progress_bar.html' with progress_container_custom_class='w-25' %}
                                {% endwith %}
                            {% else %}
                                <span class="font-5 text-muted">Non ancora recensito</span>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col site-col site-box shadow ml-3 p-4 bg-white comment-information">
                <a href="{% url 'view-public-book' book.pk %}" class="d-flex justify-content-center mb-3">
                    <img src="{{ book.cover_image_file.url }}" class="cover-img picture-big" alt="">
                </a>
                {% include "book_management/base_book_metadata_inline.html" with hide_title=True hide_authors=True %}
                <hr>
                {% with vote=book.average_rating %}
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        {% if vote is None %}
                            <h6 class="font-7">Ancora nessun voto</h6>
                        {% else %}
                            <div>
                                <h6 class="font-7 mb-0">Valutazione media</h6>
                                <span class="font-5 text-muted">
                                    {{ book.number_of_ratings }}
                                    {% if book.number_of_ratings == 1 %}voto{% else %}voti{% endif %}
                                </span>
                            </div>
                            {% include 'base_progress_bar.html' with progress_container_custom_class='w-25' %}
                        {% endif %}
                    </div>
                {% endwith %}
                <div class="d-flex column-flex align-items-end mt-5">
                    <span class="text-muted font-5 text-right">
                        <i class="fas fa-lock mr-1"></i>Pagina privata visibile solo a te
                    </span>
                    <a href="{% url 'view-public-book' book.pk %}" class="site-blue-text font-7 text-right">
                        Vai alla pagina pubblica
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/view_public_book.html
{% extends 'base.html' %}
{% load static %}
{% load book_filters %}
{% load crispy_forms_tags %}


{% comment %}
    Book public page. It contains book metadata and list of the published Topics.
{% endcomment %}

{% block title %}{{ block.super }} {{ book.title }}{% endblock %}

{% block header %}
    <div id="view-book-header-background" class="row w-100 d-flex align-items-center justify-content-center shadow">
        <span class="text-white text-center logo-font font-5 display-4 site-big-title p-2">
            {% if book.title %}
                {{ book.title|truncatewords:10 }}
            {% endif %}
            {% if book.authors_count > 0 %}
                di {{ book.authors_str|truncatewords:4 }}
            {% endif %}
        </span>
    </div>
{% endblock %}

{% block content %}
    <div class="container-fluid p-2 mb-3 bg-white w-100 site-box shadow-lg">
        <div id="view-box-information" class="row" style="display:none;">
            <div class="col-lg-auto col-12 d-flex align-items-start justify-content-center p-4">
                <div class="d-flex align-items-center justify-content-center">
                    {% if book.cover_image_file_is_default %}
                        <img src="{{ book.cover_image_file.url }}" class="img-fluid cover-img picture-big">
                    {% else %}
                        <img src="{{ book.cover_image_file.url }}" class="img-fluid cover-img">
                    {% endif %}
                </div>
            </div>
            <div class="col p-4">
                {% include 'book_management/base_book_metadata_inline.html' %}
            </div>
            <div class="col-lg-6 col-12 p-4">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h6 class="font-7">Topic</h6>
                    <span class="font-7 text-muted">{{ book.topics_count }}</span>
                </div>
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h6 class="font-7">Commenti totali</h6>
                    <span class="font-7 text-muted">{{ book.comments_count }}</span>
                </div>
                <hr>
                {% if user.has_profile %}
                    {% if book|user_saved_book:user %}
                        {% if book|user_rated_book:user %}
                            <div class="d-flex justify-content-between align-items-center mb-3">
                                {% with vote=book|get_user_book_rating:user %}
                                    <h6 class="font-7">Il tuo voto</h6>
                                    {% include 'base_progress_bar.html' with progress_container_custom_class='w-25' %}
                                {% endwith %}
                            </div>
                        {% endif %}
                    {% endif %}
                {% endif %}
                {% with vote=book.average_rating %}
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        {% if vote is None %}
                            <h6 class="font-7">Ancora nessun voto</h6>
                        {% else %}
                            <div>
                                <h6 class="font-7 mb-0">Valutazione media</h6>
                                <span class="font-5 text-muted mb-2">
                                    {{ book.number_of_ratings }}
                                    {% if book.number_of_ratings == 1 %}voto{% else %}voti{% endif %}
                                </span>
                            </div>
                            {% include 'base_progress_bar.html' with progress_container_custom_class='w-25' %}
                        {% endif %}
                    </div>
                {% endwith %}
                {% with number=book.people_reading_count %}
                    {% if number > 0 or book.is_top_5 %}
                        <div class="d-flex justify-content-between align-items-center mt-4 mb-4">
                            {% if number > 0 %}
                                <a href="#" class="people-reading-badge p-1 d-flex
                                    align-items-center font-size-90 no-decoration site-link">
                                    &nbsp;<i class="fas fa-users"></i>&nbsp;&nbsp;
                                    <span class="font-6">
                                        {{ number }}
                                        {% if number == 1 %} persona lo sta {% else %} persone lo stanno{% endif %} leggendo
                                    </span>&nbsp;
                                </a>
                            {% endif %}
                            {% if book.is_top_5 %}
                                <span class="badge badge-danger p-1 top-badge">Top 5</span>
                            {% endif %}
                        </div>
                    {% endif %}
                {% endwith %}
                <div class="d-flex justify-content-between align-items-center mb-3 bookshelf-element">
                    {% if user.is_authenticated %}
                        {% if user.has_profile %}
                            {% if book|user_saved_book:user %}
                                <h6 class="font-6 text-success mb-0">
                                    <i class="fas fa-check"></i> &nbsp;{{ book|get_user_book_status:user }}
                                </h6>
                                <a href="{% url 'view-private-book' book.pk %}" class="site-blue-text font-6">
                                    Vedi nel bookshelf
                                </a>
                            {% else %}
                                <h6 class="font-7 site-blue-text cursor-pointer" data-toggle="dropdown">
                                    + Aggiungi ai tuoi libri
                                </h6>
                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left">
                                    {% include 'user_management/bookshelf/base_dropdown_bookshefl_choices.html' with action="new" %}
                                </div>
                            {% endif %}
                        {% else %}
                            <a href="{% url 'user_management:create-profile' %}" class="site-blue-text font-7">
                                Completa il profilo per poterlo inserire nel tuo bookshelf
                            </a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="d-flex align-items-center justify-content-center cursor-pointer w-100 expand-box-data mt-2">
            <h4 class="font-7 box-data-hide">
                Informazioni libro
                <i class="fas fa-caret-down"></i>
            </h4>
            <i class="fas fa-caret-up box-data-show site-big-icon" style="display: none"></i>
        </div>
    </div>
    <div class="container-fluid p-4 mb-2 w-75 mt-4">
        <div class="row d-flex align-items-center justify-content-end">
            <a class="btn site-btn shadow" href="{% url 'comment_management:new-topic' book.pk %}">
                <i class="fas fa-plus"></i> <span class="font-7"> Nuovo Topic</span>
            </a>
            {#            <a class="btn site-btn-yellow site-btn-col ml-2" href="{% url 'comment_management:new-topic' book.pk %}">#}
            {#               <span class="font-7">Ordina per </span> <i class="fas fa-sort"></i>#}
            {#            </a>#}
        </div>
    </div>
    {% for topic in object_list %}
        <div class="site-box container-fluid shadow p-4 mb-3 bg-white w-75 comment-box">
            {% include 'comment_management/base_topic.html' %}
        </div>
    {% endfor %}
{% endblock %}

{% block extra_javascript %}
    <script src="{% static 'js/view_book.js' %}"></script>
    <script src="{% static 'js/base_topic.js' %}"></script>
    <script src="{% static 'js/show_more_less.js' %}"></script>
    <script src="{% static 'js/update_bookshelf.js' %}"></script>
    {% include 'comment_management/topic_ajax.html' %}
    {% include 'user_management/bookshelf/bookshelf_ajax.html' %}
{% endblock %}